apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - homepage-deployment.yml
  - homepage-service.yml
  - homepage-ingress.yml

configMapGenerator:
  - name: homepage
    namespace: toolbox
    files:
      - configs/settings.yaml
      - configs/services.yaml
      - configs/bookmarks.yaml
      - configs/widgets.yaml
      - configs/custom.js
      - configs/custom.css
      - configs/kubernetes.yaml
      - configs/docker.yaml
      - configs/proxmox.yaml

generatorOptions:
  disableNameSuffixHash: true