apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - portfolio-louis-deployment.yml
  - portfolio-louis-ingress.yml
  - portfolio-louis-service.yml
images:
  - name: ghcr.io/firetoak/portfolio-louis-medo
    newTag: 1.1.0
