global:
  envFrom:
    - secretRef:
        name: authentik-secrets

authentik:
  postgresql:
    host: "10.0.17.1"
    name: "db_authentik"
    user: "usr_authentik"
  email:
    host: "mail.infomaniak.com"
    port: 465
    username: "contact@loutik.fr"
    use_ssl: true
    from: "contact+authentik@loutik.fr"

server:
  resources:
    limits:
      memory: 1G
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - sso.loutik.fr

worker:
  resources:
    limits:
      memory: 512M


postgresql:
  enabled: false

redis:
  enabled: true
  master:
    resources:
      limits:
        memory: 256Mi