---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: digest-secrets
  namespace: toolbox
spec:
  encryptedData:
    MINIFLUX_TOKEN: AgAQ3rVU+FHPFW43QoZ+pUniMcH+68KKKbvMAroXpNvlhJc79G1+kkN2XX0J55OkYRMPJGFJe+t0ifEAeQziyX74SOnfLK+f3uOw6+yAn1HVLSqRtVS6NFvOwDpWxsbf4TPGv09579kAh7NyxoM0JqbF0HGZYdK28UIEO7JYT9q3WzeMt89cJ4rbc9ANqktvOb5oTtp6BWH9fc0kOKmHi/weBXDTu6B9O4mi+32BA/2PojMCP4jUim0Ydg24MxAXiw91c2WmqgwKQV+UJodenroTEWHirBfH/VYZB/bteDaMm0+uBcvz9sszqLAXZIij0jU7NDkCQko6sGFLCi3gFg5Pn1s+4faJ7sEqu/SCEz62lBwcvTp0QQz90LhIYfxL8wx6BYeb69Rl/A0gfP+Wuf9x9d2cQTEyEZGdXlo4h5VONKPpqTFIznb0cReObOggCrKksKzT16SIlaWy1z7Dewzfc0JanL74FBQkprYamzrP0SOfbfTvwnyjsH8wYBWU532fs6U2j3fin+SDjBrQU+P+kSUrogCQpIOD4hlOCIkgDAP1GZNqhGRsVXn0vT2z2kUdRl9N9CA9t1G/w538SOwHrfsSIRVWqp/hcJgKzQTulq7z7qpFRpWYs9EOc5zvRbT/ckfiwMQRb0OEVqDodXJyuBZqmUMtx1C8gNa/vKz/W0Vmwga4VDqM7KFsyhm1ssAMWCU3dodIq9ruCrZXh9D/lkBGNdAZcWxwADj9w69sthFUCZQAgiJII/k3dZcrfCl7MF8waEZgYZQPeq24xKl/
  template:
    metadata:
      name: digest-secrets
      namespace: toolbox
