---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bot-plc-secrets
  namespace: discord-bot
spec:
  encryptedData:
    DISCORD_BOT_TOKEN: AgBeKoQ+WlfMxsF3n12J0orI7bfpnZhSixGD+aEgrClAqGK1VAzq06Ra7pJ1rcMHeTFqZsjftE5GKGWs1cQf7Jm+/N/lzdgzvyBdCiemu70ZYdMnSBpRQ3YqYfO3QNZfhlm09LsvrxCjwMutbzwFKvCRwIEBrItxQJlaFeNwXr7stPAGGRHlM8Xk+CQJHPTQHiMxsovtebLWmI16ZLK6Smf54xvxpwdXi2vh7j7kIm9N++5uve6L5VZiFwF/xs8UrVTMTHks+OsnfCQ6fkuNWuBPtk11sMLqjUpaJTpFlnxDV/9kheVd53RLfW6kUGwqS55MOoH0v7QKUTck1/gOry0QFI4SoJwz6Amc6+cybS0nvZz/TwH2Lf/Itvt+Sip2oQ8p2+dNUBjCKpI3+TS47xfijjsC/fIrzIVLGGJCgtOJj5Vf2z0gospuxDSDn/5D/5ME7L68KDy7FuXi61/GJdUj/NBU3q8W69Xk1LhfoXyPTUiNrN6vPCjnXl3aoARMPHFYWwdmiv+wz0HZHjz3po2NIGEeefth3le70AYgLJ9pOULs5YWGUfstxRBt9UVScxAFhIRatQBxdPaOCSo4gDLbfdFTeTiTHHgR6+JvYGG72VeK7Znfy4tVliyhuAOFpVS4pH5Em6io8Tte0zgkCXdiss1bnkEBiSq/mjEjvrisN59yTTCnv+agMYE0byTk2Etzd2+GICN1QArQxfusn3VEKq9kutnDeYpHBrfc/sW6Y+rn64O5vUViMgZ0cmbU/5scTft8ultymnJ6e/llx6lW2BPdsMhXdq0=
    OPENWEATHER_API_KEY: AgB/BloCEPRT1YPmdyx3j2qsxlE+QWj73k7lf4Kern2yBgm/VlzFvu0DRU9u5Qp6Pv9sGRY0cE56hP4PU4nXHpiu10Xq1fU4V6xFrAdKvmdJfwqjFmNE/YWfx3X1+TPi9gWXiVF1KsEecy1lLb1mM4PRiXn85sByo2pX4yQpDG7lp8WKlj+M3u45xmfsI7lgcbOYgSaZlgl0o9q5tvFWGtWxOAJdqIPnMTNbTs2NI7PESInpys0Hy0liEL2oclFyLyBCzg/BtreeZmpdjKblMma33w8vvk2fw1uopRdfL9fxsSowGGlcpA7UUShIcsBPxV5x+88gF4Lvw3Yw4Tk0r9Ewm7g14jkLp1+mVXI5tDY6tJ6NRl0UqWuGhwnYx7puwZv1uWeyO4KjzNqr18NxELnPiTl93sKjcSgQ30sBob68inQedlhJVc9lEIm+zxag+m4qmRV+cNZ+BGiLBU4AOkv9Rvco2v6luT8FKGg8rUuyvg1hJ2SihEwJsbmJ1VXfh0ekJCfvrHzUTy7l58kvAFw7H3tVIsLv6dXF+xOoPBv5+HT0EuRHaWRUVxzCwXoMj+BJkG5e9DFxKXn/r0dydP28cytMLVNbYQgWUjLedKSDNknliRqr9uNAt4o2DVkDSd8JszcW0b/etAKQ18jxibkbp+iVD1HRfWUonh+aplQI43xwEVYm47VcseZyqGhamEpv7kWvGzfO1FLpeNuq6dnMS3JVougpc/boZwiGqeYT8Q==
  template:
    metadata:
      name: bot-plc-secrets
      namespace: discord-bot
    type: Opaque
